/* eslint-disable operator-linebreak */

// WEB3 CONTEXT
export const SET_WEB3_PROVIDER = 'SET_WEB3_PROVIDER';
export const RESET_WEB3_PROVIDER = 'RESET_WEB3_PROVIDER';

// SUPERFLUID
export const SET_SUPERFLUID_CONTRACT = 'SET_SUPERFLUID_CONTRACT';
